### ISSUE TITLE
表格没样式，代码页没有高亮

### ISSUE THREAD

**Issue by ghost** [halo-dev/halo-theme-vno#2]
<img width="911" alt="截屏2019-11-2119 02 08" src="https://user-images.githubusercontent.com/34027147/69332416-9e121d80-0c91-11ea-8766-90dae8993d04.png">

**Comment by ghost** [comment]
后台编辑正常


<img width="1125" alt="截屏2019-11-2119 06 25" src="https://user-images.githubusercontent.com/34027147/69332705-2e506280-0c92-11ea-8c8b-cde67147a4d2.png">


预览页就没有高亮了
<img width="509" alt="截屏2019-11-2119 05 51" src="https://user-images.githubusercontent.com/34027147/69332763-5049e500-0c92-11ea-87f1-28f9f69d86ba.png">

**Comment by ruibaby** [comment]
好的，感谢反馈，这个问题加个高亮插件即可。

**Comment by ghost** [comment]
> 好的，感谢反馈，这个问题加个高亮插件即可。

需要怎么加插件，是等待更新吗

**Comment by ruibaby** [comment]
等我更新吧。

**Comment by ruibaby** [comment]
@coppea 已经支持了，直接在后台更新主题即可。然后在主题设置里面启用代码高亮。
