### ISSUE TITLE
插入的图片应该靠左显示

### ISSUE THREAD

**Issue by songlongkuan** [halo-dev/halo-theme-vno#4]
如题  这个主题 插入的图片会居中显示 理应居左显示的

**Comment by gengyuanzhe** [comment]
修改Vno/css/main.css的.post img的配置，margin: 0 auto -> margin: 0 0，使图片由居中对齐变为左对齐

**Comment by gengyuanzhe** [comment]
> 如题 这个主题 插入的图片会居中显示 理应居左显示的

修改Vno/css/main.css的.post img的配置，margin: 0 auto -> margin: 0 0，使图片由居中对齐变为左对齐
